import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>VET News | News Portal Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main>
        <h1 className="text-3xl font-bold">VET News!</h1>
      </main> */}
    </div>
  );
};

export default Home;
