import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../component/Hero";
import RandomNews from "../component/RandomNews";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>VET News | News Portal Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <RandomNews />
    </div>
  );
};

export default Home;
